# Generated by Django 4.1.3 on 2023-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'it'), ('Non it', 'non it'), ('mobile phones', 'mobile phones')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
